const uxColors = {
  brand: '#EA5F09',
  tertiary: '#CBB6FF',
  neutral: '#F5E7D4',
  black: '#000000',
  secondary: '#A95C28',
  success: '#60B100',
  darkColor: '#594137',
  stroke: '#E1BFB2',
  background: '#FFFFFF',
}

const feedbackColors = {
  brandHover: '#C95008',
  error: '#BA1A1A',
  errorSoft: '#E76F51',
}

export const theme = {
  colors: {
    soft: '#FFF1EC',   
    white: '#FFFFFF',
    brand: uxColors.brand,
    tertiary: uxColors.tertiary,
    neutral: uxColors.neutral,
    black: uxColors.black,
    secondary: uxColors.secondary,
    secondaryHoverSoft: 'rgb(169 92 40 / 12%)',
    success: uxColors.success,
    darkColor: uxColors.darkColor,
    darkColorMuted: 'rgb(89 65 55 / 82%)',
    stroke: uxColors.stroke,
    background: uxColors.background,
    brandHover: feedbackColors.brandHover,
    error: feedbackColors.error,
    errorSoft: feedbackColors.errorSoft,
    statusStreetBackground: '#C5BFBF',
    statusStreetText: '#49454F',
    statusLostBackground: '#FFA49F',
    statusFoundBackground: '#CCF59B',
    statusRewardText: '#356400',
    statusAdoptionText: '#4F378A',
    statusSearchingtext: '#B3261E',
    focus: 'rgb(234 95 9 / 28%)',
    toast: {
      success: uxColors.success,
      error: feedbackColors.error,
      information: uxColors.darkColor,
    },
  },
  fonts: {
    montserrat: '"Montserrat", Arial, sans-serif',
    body: '"Montserrat", Arial, sans-serif',
  },
  fontWeights: {
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
  },
  fontSizes: {
    title: '2rem',
    subtitle: '1.5rem',
    normal: '1rem',
  },
  typography: {
    display: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: '32px',
      fontStyle: 'normal',
      fontWeight: 800,
      lineHeight: '1.2',
    },
    header1: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: '24px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '32px',
    },
    header2: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: '20px',
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: '28px',
    },
    header3: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: '16px',
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: '24px',
    },
    body: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: '14px',
      fontStyle: 'normal',
      fontWeight: 400,
      lineHeight: '20px',
    },
    descriptive: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: '12px',
      fontStyle: 'normal',
      fontWeight: 400,
      lineHeight: '16px',
    },
    action: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: '16px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '20px',
    },
    floatingAction: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: '15px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '20px',
    },
    navLabel: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: '12px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '16px',
    },
    menuItem: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: '16px',
      fontStyle: 'normal',
      fontWeight: 400,
      lineHeight: '20px',
    },
    profileName: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: '16px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '22px',
    },
    metadata: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: '12px',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '18px',
    },
    headerGreeting: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: '17px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '22px',
    },
    modalTitle: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: 'clamp(20px, 2vw, 28px)',
      fontStyle: 'normal',
      fontWeight: 800,
      lineHeight: '1.25',
    },
    modalBody: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: 'clamp(14px, 1.25vw, 18px)',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '1.55',
    },
    modalAction: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: 'clamp(14px, 1.15vw, 16px)',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '1.25',
    },
    toastTitle: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: '16px',
      fontStyle: 'normal',
      fontWeight: 800,
      lineHeight: '21px',
    },
    toastDescription: {
      fontFamily: '"Montserrat", Arial, sans-serif',
      fontSize: '13px',
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: '18px',
    },
  },
  layout: {
    contentMaxWidth: '1400px',
    mobileNavHeight: '78px',
    publicationCardWidth: '325px',
    publicationCardHeight: '400px',
  },
}

export type AppTheme = typeof theme
